# train-test split 

In [1]:
from sklearn.model_selection import train_test_split

In [2]:
#deciding the regressor and predictor variables
x=df[['c1','c2',etc...]]# give all the independent variables you want
y=df['dv']

SyntaxError: invalid syntax (<ipython-input-2-804755f75309>, line 2)

In [27]:
from sklearn import metrics

In [3]:
# working on a data set
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [4]:
lgd=pd.read_csv('LGD_DATA.csv')
lgd.head()

Ac_No  Age  Years of Experience  Number of Vehicles Gender  Married  \
0  150024   24                    5                   1      M  Married   
1  144880   31                   10                   1      F   Single   
2  133742   56                   37                   1      M  Married   
3  151282   52                   31                   1      F  Married   
4  174407   20                    3                   1      M   Single   

   Losses in Thousands  
0           203.319595  
1           402.197302  
2           553.132096  
3           292.430579  
4           246.540576

In [5]:
lgd_new=pd.get_dummies(lgd,drop_first=True)
lgd_new.head()

Ac_No  Age  Years of Experience  Number of Vehicles  Losses in Thousands  \
0  150024   24                    5                   1           203.319595   
1  144880   31                   10                   1           402.197302   
2  133742   56                   37                   1           553.132096   
3  151282   52                   31                   1           292.430579   
4  174407   20                    3                   1           246.540576   

   Gender_M  Married_Single  
0         1               0  
1         0               1  
2         1               0  
3         0               0  
4         1               1

In [6]:
x=lgd_new[['Age','Years of Experience','Number of Vehicles','Gender_M','Married_Single']]
y=lgd_new['Losses in Thousands']

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.3,random_state=1)

In [8]:
lreg=LinearRegression()
lreg.fit(x_train,y_train)
print('b0=',lreg.intercept_)
print('b1,b2,....=',lreg.coef_)

b0= 525.4414005270221
b1,b2,....= [ -5.35883861  -0.8110559   -1.7909082   97.26637702 136.80434436]


In [9]:
ytrain_predict=lreg.predict(x_train)
ytrain_predict

array([211.40138006, 232.34285105, 393.01571756, ..., 163.66295553,
       509.27774694, 337.4880472 ])

In [10]:
ytest_predict=lreg.predict(x_test)
ytest_predict

array([533.38454333, 495.47213679, 396.32803875, ..., 242.73682144,
       436.11816631, 323.28442313])

# for training model

tss,sse,mape and r2 values

In [11]:
tss_train=sum((y_train-np.mean(y_train))**2)
tss_train

689725424.274319

In [12]:
sse_train=((y_train-ytrain_predict)**2).sum()
sse_train

479656387.1153861

In [13]:
mape_train=((abs(y_train-ytrain_predict)/y_train)).sum()/(len(y_train)) #to calculate mape 
mape_train

0.6984250347680362

In [14]:
R2_train=1-(sse_train/tss_train)
R2_train

0.30456907889099916

# for test model

tss,sse,mape and r2 values

In [15]:
tss_test=sum((y_test-np.mean(y_train))**2)
tss_test

294577853.15885305

In [16]:
sse_test=((y_test-ytest_predict)**2).sum()
sse_test

207539691.18767342

In [17]:
mape_test=((abs(y_test-ytest_predict)/y_test)).sum()/(len(y_test)) #to calculate mape 
mape_test

0.7001225762919715

In [18]:
R2_test=1-(sse_test/tss_test)
R2_test

0.29546743259155916

# to calculate all values based on single function

In [25]:
ytest_predict

array([533.38454333, 495.47213679, 396.32803875, ..., 242.73682144,
       436.11816631, 323.28442313])

In [32]:
metrics.r2_score(y_test,ytest_predict)

0.2953200957211537

In [36]:
(metrics.mean_squared_error(y_test,ytest_predict))**.5

212.70917003130666